### ISSUE TITLE
No response/faulty response on OpenWRT (

### ISSUE THREAD

**Issue by misternerd** [aarond10/https_dns_proxy#120] opened 2021-06-27 17:10 UTC
Good evening,
I'm having an issue with https-dns-proxy on my OpenWRT router. Arbitrarily, the proxy stops answering any DNS requests. During these outages, I see a stable CPU load of 25% of the proxy process and repeatedly the following two log messages:

```
Sun Jun 27 18:39:56 2021 daemon.info https-dns-proxy[11584]: [E] 1624811996.081672 https_client.c:205 No response
Sun Jun 27 18:40:01 2021 daemon.info https-dns-proxy[11584]: [I] 1624811996.081749 https_client.c:339 Response was faulty, skipping DNS reply.
```

No other log messages are being displayed by the proxy. The outages happen randomly and mostly the proxy starts working again after a few minutes. I tried it with different providers (among them Cloudflare, Cloudflare Secure and OpenDNS), 

I updated all packages on my router yesterday. The proxy is at version `2021-06-03-1` and starts with

```
Sun Jun 27 18:39:43 2021 daemon.info https-dns-proxy[11584]: [I] 1624811983.440842 main.c:207 Built Jun 14 2021 09:52:25.
Sun Jun 27 18:39:43 2021 daemon.info https-dns-proxy[11584]: [I] 1624811983.440867 main.c:208 System c-ares: 1.15.0
Sun Jun 27 18:39:43 2021 daemon.info https-dns-proxy[11584]: [I] 1624811983.441024 main.c:209 System libcurl: libcurl/7.66.0 mbedTLS/2.16.10
Sun Jun 27 18:39:43 2021 daemon.info https-dns-proxy[11584]: [I] 1624811983.441397 dns_server.c:50 Listening on 127.0.0.1:5053
Sun Jun 27 18:39:43 2021 daemon.info https-dns-proxy[11584]: [I] 1624811983.441831 main.c:272 DNS polling initialized for 'doh.opendns.com'
Sun Jun 27 18:39:54 2021 daemon.info https-dns-proxy[11584]: [E] 1624811994.729976 https_client.c:117 CURLOPT_HTTP_VERSION error 1: Error
Sun Jun 27 18:39:54 2021 daemon.info https-dns-proxy[11584]: [E] 1624811994.730134 https_client.c:119 Try to run application with -x argument! Forcing HTTP/1.1 version.
```

The effective command (here with Cloudflare) of the running daemon is: `/usr/sbin/https-dns-proxy -r https://cloudflare-dns.com/dns-query -a 127.0.0.1 -p 5053 -b 1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001 -u nobody -g nogroup -v -v -4`

Please let me know what I can do to investigate and fix the problem. Looking at the other issues, I didn't find any similar log messages.

**Comment by baranyaib90** [comment] 2021-06-28 05:34
Hi,
first of all, if you are using `-4` option, please do not add IPv6 resolver addresses for the `-b` bootstrap resolvers option.
The strange thing is, that `No response` error always should come with a curl error message pair.
Example:  if the TCP connection was opened a very long time ago, then the following error message should present: `curl response code: 500, content length: 0`
In case a connection timeout or other errors (that could occur during internet outage) a corresponding curl error message should present.
If this happens very often or if you can reproduce it, please provide debug level logs (adding an extra `-v` option).
For now I have no explanation about the high CPU usage.

**Comment by baranyaib90** [comment] 2021-06-29 05:21
Sorry, I was a bit mistaken. Actually `No response` is the curl [error log](https://github.com/aarond10/https_dns_proxy/blob/master/src/https_client.c#L282) pair.
This means, that the connection to the HTTPS server has been timeouted or closed.
This can happen very often and it's not a huge problem. I guess it could be a warning instead of an error.
You should not worry, since clients will retry the DNS lookup so there won't be any problem.

**Comment by misternerd** [comment] 2021-06-30 06:09
After disabling the IPv6 addresses for the bootstrap resolvers, the proxy seems to be running much smoother (only tested for the last 24 hours, though). But I still get the errors sometimes. I increased the log level and get these log messages. I checked and this wasn't during a DSL reconnect.
```
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020123.446355 https_client.c:438 Reserved new io event: 0xbef0bbc8
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020123.446473 main.c:101 Received request for id: 0439, len: 50
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020123.446522 https_client.c:111 Requesting HTTP/1.1: 1
Jun 30 04:28:49 router https-dns-proxy[20057]:
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020123.452618 https_client.c:55 curl opened socket: 13
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020123.453000 https_client.c:438 Reserved new io event: 0xbef0bbe8
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020124.782964 https_client.c:428 Released used io event: 0xbef0bb88
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020124.782990 https_client.c:438 Reserved new io event: 0xbef0bb88
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020126.097900 https_client.c:428 Released used io event: 0xbef0bba8
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020126.097928 https_client.c:438 Reserved new io event: 0xbef0bba8
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020127.397095 https_client.c:428 Released used io event: 0xbef0bbc8
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020127.397122 https_client.c:438 Reserved new io event: 0xbef0bbc8
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020128.706411 https_client.c:428 Released used io event: 0xbef0bbe8
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020128.706438 https_client.c:438 Reserved new io event: 0xbef0bbe8
Jun 30 04:28:49 router https-dns-proxy[20057]: [D] 1625020129.653639 main.c:101 Received request for id: 98e3, len: 48
Jun 30 04:28:49 router https-dns-proxy[20057]: > POST /dns-query HTTP/1.1
Jun 30 04:28:49 router https-dns-proxy[20057]: Host: cloudflare-dns.com
Jun 30 04:28:49 router https-dns-proxy[20057]: User-Agent: dns-to-https-proxy/0.2
Jun 30 04:28:49 router https-dns-proxy[20057]: Accept: application/dns-message
Jun 30 04:28:49 router https-dns-proxy[20057]: Content-Type: application/dns-message
Jun 30 04:28:49 router https-dns-proxy[20057]: Content-Length: 44
Jun 30 04:28:49 router https-dns-proxy[20057]:
Jun 30 04:28:49 router https-dns-proxy[20057]: > POST /dns-query HTTP/1.1
Jun 30 04:28:49 router https-dns-proxy[20057]: Host: cloudflare-dns.com
Jun 30 04:28:49 router https-dns-proxy[20057]: User-Agent: dns-to-https-proxy/0.2
Jun 30 04:28:49 router https-dns-proxy[20057]: Accept: application/dns-message
Jun 30 04:28:49 router https-dns-proxy[20057]: Content-Type: application/dns-message
Jun 30 04:28:49 router https-dns-proxy[20057]: Content-Length: 48
Jun 30 04:28:49 router https-dns-proxy[20057]:
Jun 30 04:28:49 router https-dns-proxy[20057]: > POST /dns-query HTTP/1.1
Jun 30 04:28:49 router https-dns-proxy[20057]: Host: cloudflare-dns.com
Jun 30 04:28:49 router https-dns-proxy[20057]: User-Agent: dns-to-https-proxy/0.2
Jun 30 04:28:49 router https-dns-proxy[20057]: Accept: application/dns-message
Jun 30 04:28:49 router https-dns-proxy[20057]: Content-Type: application/dns-message
Jun 30 04:28:49 router https-dns-proxy[20057]: Content-Length: 49
Jun 30 04:28:49 router https-dns-proxy[20057]:
Jun 30 04:28:49 router https-dns-proxy[20057]: > POST /dns-query HTTP/1.1
Jun 30 04:28:49 router https-dns-proxy[20057]: Host: cloudflare-dns.com
Jun 30 04:28:49 router https-dns-proxy[20057]: User-Agent: dns-to-https-proxy/0.2
Jun 30 04:28:49 router https-dns-proxy[20057]: Accept: application/dns-message
Jun 30 04:28:49 router https-dns-proxy[20057]: Content-Type: application/dns-message
Jun 30 04:28:49 router https-dns-proxy[20057]: Content-Length: 50
Jun 30 04:28:49 router https-dns-proxy[20057]:
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.653692 https_client.c:111 Requesting HTTP/1.1: 1
Jun 30 04:28:50 router https-dns-proxy[20057]:
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.654128 https_client.c:55 curl opened socket: 14
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.654438 https_client.c:438 Reserved new io event: 0xbef0bc08
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.657623 main.c:101 Received request for id: 460a, len: 44
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.657687 https_client.c:111 Requesting HTTP/1.1: 1
Jun 30 04:28:50 router https-dns-proxy[20057]:
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.658050 https_client.c:55 curl opened socket: 15
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.658339 https_client.c:438 Reserved new io event: 0xbef0bc28
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.658391 main.c:101 Received request for id: 0439, len: 50
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.658472 https_client.c:111 Requesting HTTP/1.1: 1
Jun 30 04:28:50 router https-dns-proxy[20057]:
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.658867 https_client.c:55 curl opened socket: 16
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.659140 https_client.c:438 Reserved new io event: 0xbef0bc48
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.659236 main.c:101 Received request for id: 4dec, len: 49
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.659328 https_client.c:111 Requesting HTTP/1.1: 1
Jun 30 04:28:50 router https-dns-proxy[20057]:
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.662662 https_client.c:55 curl opened socket: 17
Jun 30 04:28:50 router https-dns-proxy[20057]: [D] 1625020129.662945 https_client.c:438 Reserved new io event: 0xbef0bc68
Jun 30 04:28:54 router https-dns-proxy[20057]: [D] 1625020130.968959 https_client.c:428 Released used io event: 0xbef0bc08
Jun 30 04:28:54 router https-dns-proxy[20057]: [D] 1625020130.971670 https_client.c:438 Reserved new io event: 0xbef0bc08
Jun 30 04:28:54 router https-dns-proxy[20057]: [D] 1625020132.270139 https_client.c:428 Released used io event: 0xbef0bc28
Jun 30 04:28:54 router https-dns-proxy[20057]: [D] 1625020132.270167 https_client.c:438 Reserved new io event: 0xbef0bc28
Jun 30 04:28:54 router https-dns-proxy[20057]: [D] 1625020133.569415 https_client.c:428 Released used io event: 0xbef0bc48
Jun 30 04:28:54 router https-dns-proxy[20057]: [D] 1625020133.569443 https_client.c:438 Reserved new io event: 0xbef0bc48
Jun 30 04:28:54 router https-dns-proxy[20057]: [D] 1625020134.881485 https_client.c:428 Released used io event: 0xbef0bc68
Jun 30 04:28:54 router https-dns-proxy[20057]: [D] 1625020134.881512 https_client.c:438 Reserved new io event: 0xbef0bc68
Jun 30 04:28:54 router https-dns-proxy[20057]: * Operation timed out after 11453 milliseconds with 0 bytes received
Jun 30 04:28:54 router https-dns-proxy[20057]: * Operation timed out after 11436 milliseconds with 0 bytes received
Jun 30 04:28:54 router https-dns-proxy[20057]: * Operation timed out after 11435 milliseconds with 0 bytes received
Jun 30 04:28:54 router https-dns-proxy[20057]: * Operation timed out after 11429 milliseconds with 0 bytes received
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020134.883188 https_client.c:428 Released used io event: 0xbef0bb88
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020134.883219 https_client.c:87 curl closed socket: 10
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020134.884843 https_client.c:428 Released used io event: 0xbef0bba8
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020134.884871 https_client.c:87 curl closed socket: 11
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020134.886408 https_client.c:428 Released used io event: 0xbef0bbc8
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020134.886438 https_client.c:87 curl closed socket: 12
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020134.887941 https_client.c:428 Released used io event: 0xbef0bbe8
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020134.887972 https_client.c:87 curl closed socket: 13
Jun 30 04:28:55 router https-dns-proxy[20057]: [E] 1625020135.841324 https_client.c:205 No response
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841417 https_client.c:260 CURLINFO_NUM_CONNECTS: 1
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841435 https_client.c:272 CURLINFO_EFFECTIVE_URL: https://cloudflare-dns.com/dns-query
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841448 https_client.c:289 CURLINFO_HTTP_VERSION: 0
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841467 https_client.c:321 Times: 0.016365, 0.028976, 6.227388, 6.227699, 0.000000, 11.454001
Jun 30 04:28:55 router https-dns-proxy[20057]: [I] 1625020135.841503 https_client.c:339 Response was faulty, skipping DNS reply.
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841515 main.c:81 buflen 0
Jun 30 04:28:55 router https-dns-proxy[20057]:
Jun 30 04:28:55 router https-dns-proxy[20057]: [E] 1625020135.841605 https_client.c:205 No response
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841635 https_client.c:260 CURLINFO_NUM_CONNECTS: 1
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841648 https_client.c:272 CURLINFO_EFFECTIVE_URL: https://cloudflare-dns.com/dns-query
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841661 https_client.c:289 CURLINFO_HTTP_VERSION: 0
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841675 https_client.c:321 Times: 0.000303, 1.338263, 6.212294, 6.212618, 0.000000, 11.438496
Jun 30 04:28:55 router https-dns-proxy[20057]: [I] 1625020135.841705 https_client.c:339 Response was faulty, skipping DNS reply.
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841716 main.c:81 buflen 0
Jun 30 04:28:55 router https-dns-proxy[20057]:
Jun 30 04:28:55 router https-dns-proxy[20057]: [E] 1625020135.841774 https_client.c:205 No response
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841797 https_client.c:260 CURLINFO_NUM_CONNECTS: 1
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841811 https_client.c:272 CURLINFO_EFFECTIVE_URL: https://cloudflare-dns.com/dns-query
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841823 https_client.c:289 CURLINFO_HTTP_VERSION: 0
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841837 https_client.c:321 Times: 0.000179, 2.652164, 6.210278, 6.210613, 0.000000, 11.439191
Jun 30 04:28:55 router https-dns-proxy[20057]: [I] 1625020135.841865 https_client.c:339 Response was faulty, skipping DNS reply.
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841875 main.c:81 buflen 0
Jun 30 04:28:55 router https-dns-proxy[20057]:
Jun 30 04:28:55 router https-dns-proxy[20057]: [E] 1625020135.841931 https_client.c:205 No response
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841954 https_client.c:260 CURLINFO_NUM_CONNECTS: 1
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841967 https_client.c:272 CURLINFO_EFFECTIVE_URL: https://cloudflare-dns.com/dns-query
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841981 https_client.c:289 CURLINFO_HTTP_VERSION: 0
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.841995 https_client.c:321 Times: 0.000210, 3.944826, 6.211335, 6.212794, 0.000000, 11.434206
Jun 30 04:28:55 router https-dns-proxy[20057]: [I] 1625020135.842021 https_client.c:339 Response was faulty, skipping DNS reply.
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.842032 main.c:81 buflen 0
Jun 30 04:28:55 router https-dns-proxy[20057]:
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.842245 main.c:101 Received request for id: 9f6a, len: 37
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.842285 https_client.c:111 Requesting HTTP/1.1: 1
Jun 30 04:28:55 router https-dns-proxy[20057]:
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.842615 https_client.c:55 curl opened socket: 18
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.842937 https_client.c:438 Reserved new io event: 0xbef0bb88
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.845836 main.c:101 Received request for id: 6e47, len: 37
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.845881 https_client.c:111 Requesting HTTP/1.1: 1
Jun 30 04:28:55 router https-dns-proxy[20057]:
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.846263 https_client.c:55 curl opened socket: 19
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.846656 https_client.c:438 Reserved new io event: 0xbef0bba8
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.846725 main.c:101 Received request for id: 164e, len: 33
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.846804 https_client.c:111 Requesting HTTP/1.1: 1
Jun 30 04:28:55 router https-dns-proxy[20057]:
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.847174 https_client.c:55 curl opened socket: 20
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.847450 https_client.c:438 Reserved new io event: 0xbef0bbc8
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.847502 main.c:101 Received request for id: 1386, len: 33
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.847537 https_client.c:111 Requesting HTTP/1.1: 1
Jun 30 04:28:55 router https-dns-proxy[20057]:
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.847862 https_client.c:55 curl opened socket: 21
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.848118 https_client.c:438 Reserved new io event: 0xbef0bbe8
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.848168 main.c:101 Received request for id: 1ecb, len: 39
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.848203 https_client.c:111 Requesting HTTP/1.1: 1
Jun 30 04:28:55 router https-dns-proxy[20057]:
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.848471 main.c:101 Received request for id: e114, len: 39
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.848508 https_client.c:111 Requesting HTTP/1.1: 1
Jun 30 04:28:55 router https-dns-proxy[20057]:
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.848717 main.c:101 Received request for id: 1910, len: 37
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.848752 https_client.c:111 Requesting HTTP/1.1: 1
Jun 30 04:28:55 router https-dns-proxy[20057]:
Jun 30 04:28:55 router https-dns-proxy[20057]: [D] 1625020135.848974 main.c:101 Received request for id: ec1b, len: 37
```

**Comment by baranyaib90** [comment] 2021-06-30 06:34
Thank you for the debug logs!
It is clear, that this is a connection issue:
```
Jun 30 04:28:54 router https-dns-proxy[20057]: * Operation timed out after 11453 milliseconds with 0 bytes received
Jun 30 04:28:54 router https-dns-proxy[20057]: * Operation timed out after 11436 milliseconds with 0 bytes received
Jun 30 04:28:54 router https-dns-proxy[20057]: * Operation timed out after 11435 milliseconds with 0 bytes received
Jun 30 04:28:54 router https-dns-proxy[20057]: * Operation timed out after 11429 milliseconds with 0 bytes received
```
The timeout is 10 seconds, and this means, that the proxy wants to connect to the remote host, but it can not.
Example in case of socket 13:
```
[D] 1625020123.452618 https_client.c:55 curl opened socket: 13
                      11.435354 sec time difference
[D] 1625020134.887972 https_client.c:87 curl closed socket: 13
```
This is very strange, since the proxy could connect to the remote host, it could send the request, but does not have received any response within 10 seconds. And cloudflare is a slow provider.

I suggest to optimize the cloudflare resolver URL or server IP lookup if you can. Try the following separately:

1. Set "https://1.1.1.1/dns-query" as resolver URL
2. With debug logs, check a successful response header: cf-ray value should be close to your country (last 3 letter is server's country code). You could even change the bootstrap DNS server to lookup "cloudflare-dns.com" more optimized, so you could receive closer server IPs to your country.

**Comment by misternerd** [comment] 2021-06-30 17:33
Thanks for your help, @baranyaib90! Unfortunately, I have the feeling that this might be some weird OpenWRT issue.

Here's what I tried since my last post:
1. Setting the resolver to `https://1.1.1.1` doesn't work, as the CA certificates installed on OpenWRT don't allow that certificate. I tried installing `ca-certificates` (`ca-bundle` was already installed), but still no luck (verified with cURL call in shell, getting ![Selection_001](https://user-images.githubusercontent.com/4542322/124005049-f0bccb00-d9d8-11eb-8333-ae377cc21325.jpg)
2. I tried using my provider's DNS server for initial lookup, but that actually gives me the same datacenter as using 1.1.1.1
3. Today, I already had multiple outages where the proxy didn't work for some minutes. Even multiple restarts didn't help, it always ended up with a faulty/no response. During the outage, I manually executed cURL calls to Cloudflare and they worked (404 cause I did GET requests, but still). Also, the whole time, the proxy maintains a steady 25% CPU load (see screenshot). After 3-4 restarts, it finally worked again. Looking at my logs now, I had this a few more times today and it always took at least a minute before settling back.

If there's nothing else I can try, I'd open an issue in OpenWRT, maybe there's an issue with dnsmasq, as I can always see some DHCP traffic before the issue starts appearing.

**Comment by baranyaib90** [comment] 2021-07-01 13:43
You could try this: https://github.com/aarond10/https_dns_proxy/issues/106#issuecomment-858459047
But I have no other ideas.

**Comment by stangri** [comment] 2021-07-27 10:12
@baranyaib90 @aarond10 

> first of all, if you are using `-4` option, please do not add IPv6 resolver addresses for the `-b` bootstrap resolvers option.

The `-4` option is added by default by the OpenWrt init script (unless manually overridden) as on the legacy-only systems the proxy doesn't seem to work without it. Should I add code to the init script to strip IPv6 bootstrap servers from the parameters then?

Or would it be better to add logic to ignore IPv6 bootstrap addresses when `-4` is used to the principal/binary?

**Comment by baranyaib90** [comment] 2021-07-28 14:36
It would be great if you could do it in the init script.
For now I would not do such stuff in the code.

Actually I don't have IPv6 address... So I can not test it properly.
If the following works: `./https_dns_proxy -v -v -v -4 -b 2606:4700:4700::1111`
Without having `DNS lookup failed: Could not contact DNS servers` logs, IPv6 addresses could remain (but better at the end of the list).

**Comment by stangri** [comment] 2021-07-29 05:27
I've updated the init script, waiting for your commit to be merged so I can create PR and merge changes into OpenWrt packages.

Without the `-4`, on OpenWrt the https_dns_proxy fails to resolve anything on the legacy-IP only systems, hence unless it's overridden thru a setting, it's a default on OpenWrt:

```
SG-105 in ~ # https-dns-proxy -r https://cloudflare-dns.com/dns-query -b 1.1.1.1,1.0.0.1 -p 5055 -x -vvvvv
----------------------------
WARNING: Running as root without dropping privileges is NOT recommended.
----------------------------
[I] 1627536290.584204 main.c:207 Built Jun 13 2021 22:02:19.
[I] 1627536290.584236 main.c:208 System c-ares: 1.17.1
[I] 1627536290.584304 main.c:209 System libcurl: libcurl/7.77.0 wolfSSL/4.7.0
[I] 1627536290.584693 dns_server.c:50 Listening on 127.0.0.1:5055
[D] 1627536290.584724 logging.c:39 starting periodic log flush timer
[D] 1627536290.584950 dns_poller.c:177 Nameservers count: 2
[I] 1627536290.584976 main.c:272 DNS polling initialized for 'cloudflare-dns.com'
[D] 1627536290.585009 dns_poller.c:113 Starting DNS query
[D] 1627536290.585118 dns_poller.c:41 Reserved new io event: 0x40bf60
[D] 1627536290.585244 dns_poller.c:125 DNS poll interval changed to: 0.700
[D] 1627536290.586881 main.c:173 Received new DNS server IP '2606:4700::6810:f8f9,2606:4700::6810:f9f9'
[D] 1627536290.587049 dns_poller.c:88 DNS poll interval changed to: 120
[D] 1627536290.587088 dns_poller.c:31 Released used io event: 0x40bf60
[D] 1627536296.483939 main.c:101 Received request for id: 1fa0, len: 27
[D] 1627536296.484015 https_client.c:111 Requesting HTTP/1.1: 1

[D] 1627536296.484200 https_client.c:55 curl opened socket: 8
[D] 1627536296.484263 https_client.c:87 curl closed socket: 8
[D] 1627536296.484287 https_client.c:55 curl opened socket: 9
[D] 1627536296.484325 https_client.c:87 curl closed socket: 9
[E] 1627536296.484353 https_client.c:205 No response
```

**Comment by baranyaib90** [comment] 2021-07-29 06:05
OK, let's keep it this way, with `-4` as it was.
The thing is, that this IPv4/6 stuff should be fixed properly one day.

**Closed** 2021-11-06 23:26 UTC
