### ISSUE TITLE
Not working (sometimes)?

### ISSUE THREAD

**Issue by jefferyto** [aarond10/https_dns_proxy#40] opened 2018-06-13 14:44 UTC
My apologies in advance as this may not be a very good bug report. I've spent a lot of time trying to get the proxy to work reliably, but I'm still not clear what it going wrong.

I'm running LEDE 17.01.4 on a TP-Link Archer C7 v2, and I built the 2018-04-23 version of https_dns_proxy, based on the current [Makefile](https://github.com/openwrt/packages/blob/f74f517b9a33924e3430b7daf6f85a3b777279e0/net/https-dns-proxy/Makefile) in the packages feed.

(As a side note, it would be nice if the DNS polling timeout was adaptive or at least shorter. I initially had the proxy started on boot only, but because the network wasn't ready yet, the DNS lookup would fail and it would wait 2 minutes to retry. I now have a hotplug script to restart the proxy whenever a network interface goes up, that seems to have bypassed the wait.)

Sometimes when the proxy is started, usually at boot or soon after, in the debug log I can see requests:

```
[D] 1528893225.373079 main.c:115 Received request for 'www.icloud.com' id: ffda, type 28, flags 0100
[D] 1528893225.373549 https_client.c:57 Requesting HTTP/1.1: 1

[D] 1528893225.789908 main.c:115 Received request for 'www.icloud.com' id: 4048, type 1, flags 0100
[D] 1528893225.790256 https_client.c:57 Requesting HTTP/1.1: 1
```

but the responses will have 0 length:

```
[D] 1528893226.830422 https_client.c:96 CURLINFO_EFFECTIVE_URL: https://cloudflare-dns.com/dns-query?ct=application/dns-json&name=www.icloud.com&type=1
[D] 1528893226.830473 https_client.c:108 CURLINFO_RESPONSE_CODE: 0
[D] 1528893226.830491 https_client.c:169 Times: 0.000246, 0.242603, 0.000000, 0.000000, 0.000000, 2.250143
[D] 1528893226.830551 main.c:80 buflen 0

[D] 1528893226.830580 https_client.c:96 CURLINFO_EFFECTIVE_URL: https://cloudflare-dns.com/dns-query?ct=application/dns-json&name=www.icloud.com&type=28
[D] 1528893226.830598 https_client.c:108 CURLINFO_RESPONSE_CODE: 0
[D] 1528893226.830616 https_client.c:169 Times: 0.000247, 0.297239, 0.000000, 0.000000, 0.000000, 2.259714
[D] 1528893226.830672 main.c:80 buflen 0
```

I've used the `-x` switch (and it says it's using HTTP/1.1 for requests) but it doesn't seem to help. If I restart the proxy (either manually or automatically by my hotplug script), sometimes it will get responses with actual JSON content.

I'd really like to have this resolved, as I don't want to worry about my DNS not working whenever my router is restarted :laughing:

**Comment by Wintereise** [comment] 2018-08-08 13:08
I'm still seeing this on the bundled OpenWRT package on 18.06 (latest). Specific version (according to opkg) is:

`https_dns_proxy - 2018-04-23-1`

When it happens, the requests keep piling on, but nothing ever receives a response

```
[D] 1533733105.053968 main.c:115 Received request for 'kotlinlang.slack.com' id: 87e6, type 1, flags 0100
[D] 1533733105.054208 https_client.c:57 Requesting HTTP/1.1: 0

[D] 1533733105.079849 https_client.c:96 CURLINFO_EFFECTIVE_URL: https://dns.google.com/resolve?name=vpsdime.com&type=1
[D] 1533733105.079909 https_client.c:108 CURLINFO_RESPONSE_CODE: 0
[D] 1533733105.079929 https_client.c:169 Times: 0.000301, 0.643964, 0.000000, 0.000000, 0.000000, 10.830928
[D] 1533733105.080029 main.c:80 buflen 0

[D] 1533733107.196932 https_client.c:96 CURLINFO_EFFECTIVE_URL: https://dns.google.com/resolve?name=mpmulti-n89o.lb.slack-msgs.com&type=1
[D] 1533733107.196972 https_client.c:108 CURLINFO_RESPONSE_CODE: 0
[D] 1533733107.196992 https_client.c:169 Times: 0.000340, 0.073105, 1.048310, 0.000000, 0.000000, 20.467436
[D] 1533733107.197212 main.c:80 buflen 0

[D] 1533733107.197252 https_client.c:96 CURLINFO_EFFECTIVE_URL: https://dns.google.com/resolve?name=mpmulti-fs1i.lb.slack-msgs.com&type=1
[D] 1533733107.197332 https_client.c:108 CURLINFO_RESPONSE_CODE: 0
[D] 1533733107.197372 https_client.c:169 Times: 0.000320, 0.108367, 0.000000, 0.000000, 0.000000, 10.787745
[D] 1533733107.197452 main.c:80 buflen 0

[D] 1533733107.197492 https_client.c:96 CURLINFO_EFFECTIVE_URL: https://dns.google.com/resolve?name=imap.gmail.com&type=1
[D] 1533733107.197512 https_client.c:108 CURLINFO_RESPONSE_CODE: 0
[D] 1533733107.197552 https_client.c:169 Times: 0.000300, 0.902781, 0.000000, 0.000000, 0.000000, 10.792285
[D] 1533733107.197612 main.c:80 buflen 0

[D] 1533733107.197692 main.c:115 Received request for 'vpsdime.com' id: b527, type 1, flags 0100
[D] 1533733107.197912 https_client.c:57 Requesting HTTP/1.1: 0

[D] 1533733107.204012 https_client.c:96 CURLINFO_EFFECTIVE_URL: https://dns.google.com/resolve?name=imap.gmail.com&type=1
[D] 1533733107.204052 https_client.c:108 CURLINFO_RESPONSE_CODE: 0
[D] 1533733107.204072 https_client.c:169 Times: 0.000320, 0.601320, 0.000000, 0.000000, 0.000000, 10.804266
[D] 1533733107.204172 main.c:80 buflen 0

[D] 1533733107.204292 main.c:115 Received request for 'mail.google.com' id: 71e3, type 1, flags 0100
[D] 1533733107.204512 https_client.c:57 Requesting HTTP/1.1: 0

[D] 1533733107.212673 https_client.c:96 CURLINFO_EFFECTIVE_URL: https://dns.google.com/resolve?name=discovery-v6.syncthing.net&type=1
[D] 1533733107.212713 https_client.c:108 CURLINFO_RESPONSE_CODE: 0
[D] 1533733107.212733 https_client.c:169 Times: 0.000300, 0.547176, 0.000000, 0.000000, 0.000000, 10.812146
[D] 1533733107.212853 main.c:80 buflen 0

[D] 1533733107.218373 https_client.c:96 CURLINFO_EFFECTIVE_URL: https://dns.google.com/resolve?name=discovery-v4.syncthing.net&type=1
[D] 1533733107.218413 https_client.c:108 CURLINFO_RESPONSE_CODE: 0
[D] 1533733107.218433 https_client.c:169 Times: 0.000320, 0.497813, 0.000000, 0.000000, 0.000000, 17.283362
[D] 1533733107.218533 main.c:80 buflen 0
```

CPU usage also hits 100%. It's not specific to a specific resolver (I've ran into it using both Google and Cloudflare).

Running on  OpenWrt 18.06.0, r7188-b0b5c64c22

**Comment by aarond10** [comment] 2018-08-09 10:36
That zero size replies are pretty odd. I'm wondering if it's something HTTP2-related as the majority of connection issues reported have been somehow related to libcurl and http2 support in particular. I'm running this on an x86 box these days and haven't had any issues. I'd love to know what a pprof or even just a stack trace says it's doing here. Are you able to drive gdb by any chance?

**Comment by Wintereise** [comment] 2018-08-09 10:37
Hi gdb is fine if you tell me what to look for.

Otherwise I can get you a strace. The specific environment this is running on is mipsel / xiaomi miwifi mini r1cm

@aarond10

**Comment by aarond10** [comment] 2018-08-09 10:48
Forget gdb then. An strace log would definitely be a good start. :)
Can you also confirm the version of libcurl you're using (it'll appear in debug logs near the start) so I can try to replicate what you're seeing?

**Comment by Wintereise** [comment] 2018-08-09 10:50
Hi,

Here are the versions:

```
[I] 1533811769.069342 main.c:177 Built Jul 21 2018 18:53:43.
[I] 1533811769.070082 main.c:178 System c-ares: 1.14.0
[I] 1533811769.070902 main.c:179 System libcurl: libcurl/7.60.0 mbedTLS/2.8.0
```

As to the strace, it's currently not happening (though has a habit of happening at least once per day). I'll let you know when I manage to collect the trace.

**Comment by mrhso** [comment] 2018-08-10 02:25
The problem can be reproduced. Running on OpenWrt 18.06.0 r7188-b0b5c64c22 (latest).

**Comment by Wintereise** [comment] 2018-08-10 12:54
@aarond10 sent you an email with the strace.

**Comment by aarond10** [comment] 2018-09-05 11:11
I've just gone through your strace file. I was suspecting a few things, none of which seem obviously wrong. 

System time is correct. The trace is for about 10 seconds but it reads your system ssl certificate file 26 times and tries to connect to the SSL server 29 times. Ouch! At that rate, I imagine Google is going to block your IP for a short while. As to why it's getting into this state, I'm not sure. It doesn't appear to be getting far enough to set up HTTP/2 with pipelining, etc. 

Do you hit this instance with a lot of concurrent requests? Given these things are being translated into fairly expensive SSL requests, there may be a practical limit to how hard you can hit it without being cut off. Can you try with cloudflare and tell me if you have the same symptoms?

**Comment by Wintereise** [comment] 2018-09-05 11:15
dnsmasq in front, not really being hit hard at all. What I replaced this with (pi-hole) is at some 10k queries over a 1.5 week period.

Yes, the symptoms happen regardless of Google or Cloudflare (I ran it with both simultaneously, multiple instances).

**Comment by aarond10** [comment] 2018-09-05 11:50
I've been running on x86 now for a few weeks without a hiccup. I switched when openwrt (lede) libcurl broke HTTP/2 but that's been fixed a while. I'll switch back and try to replicate.

**Comment by tofurky** [comment] 2018-09-07 15:28
i'm seeing the same thing on boot. this wasn't an issue on lede 17.01.4 running daemonized without procd.

what appears to be happening is libcares is trying to bootstrap using `127.0.0.1#53` even though it's being passed `-b 1.1.1.1,1.0.0.1`.  i can see it opening resolv.conf in strace etc. of course this results in a loop of sorts.

eventually, a minute or 2 after boot, a request will finally be sent to 1.1.1.1 and dns will work from there on.

so, i'll try to figure out why c-ares seems to be falling back to resolv.conf and report back if i find anything.

**Comment by tofurky** [comment] 2018-09-07 19:00
i just spent a couple hours trying to figure this out to no avail.

i added tracing all throughout ares_init.c to track down any codepaths that might be introducing 127.0.0.1 or the contents of resolv.conf to the list of nameservers.

even after modifying dns_poller.c to provide every option to ares_init_options() so that the codepath which reached init_by_defaults() and init_by_resolv_conf() wasn't hit, it is *still* trying to bootstrap via 127.0.0.1#53.

downgrading to c-ares 1.13.0 didn't fix it either. i'm stumped 😩

i did focus mainly on ares_init.c but perhaps it's falling back to resolv.conf in another file. i also didn't try reverting to using it daemonized without running in the foreground under procd like i was before.

look forward to seeing if anyone else finds something.

**Comment by tofurky** [comment] 2018-09-09 06:17
nope. a lot of my debugging was executing from rc.local like this:
`/usr/sbin/https_dns_proxy -a 127.0.0.1 -p 5053 -b 1.1.1.1,1.0.0.1 -r https://cloudflare-dns.com/dns-query?ct=application/dns-json\& -u nobody -g nogroup -vvvv >>/tmp/https.debug 2>&1`

as a workaround maybe adding something to the openwrt init script like procd_add_interface_trigger for when wan comes up could help?

anyhow, i had a super long detailed reply written up regarding tracing the code paths in libcares, but i think i was looking in the wrong place the entire time. it's not c-ares grabbing the nameserver from resolv.conf or defaulting to localhost.

it appears that when the initial bootstrap fails, it doesn't try again for 120s:
```
      dns_poller_init(&dns_poller, loop, opt.bootstrap_dns, hostname,
                      120 /* seconds */, dns_poll_cb, &app.resolv);
```
this explains the long delay after boot.

even after failing, it seems to attempt to make requests with CURL anyways, which explains the traffic to the nameserver set in resolv.conf, in my case localhost. it's using standard gethostbyname() and checking /etc/hosts and resolv.conf. this is visible via strace.

so i think 2 things need to happen:
1.) shorter retry interval if the dns request fails, to more quickly bootstrap upon failure
2.) perhaps don't make requests with CURL until the resolver ip has been bootstrapped

**Comment by tofurky** [comment] 2018-09-09 06:42
btw, i just realized why i hadn't encountered the issue before. i installed https_dns_proxy on my router without ever having rebooted it. it was up for 100+ days when i installed/configured it, and up for another 100 days before i then switched routers and temporarily wasn't using it on the new one.

so, to be clear, this issue had nothing to do with LEDE vs OpenWRT  or c-ares versions.

**Comment by aarond10** [comment] 2018-09-09 22:54
This is great to hear. I imagine you're probably seeing a race where
https_dns_proxy comes up before your network is ready. Exponential backoff
on DNS up to once every 2 minutes sounds reasonable. I'll run with that.

**Comment by aarond10** [comment] 2018-09-10 00:44
I've had a look at this but the options I have are all a bit ugly and have me wondering if it's your network interface devices that haven't come up in time perhaps?

The options I considered were:
1. *Exponential backoff* - Already done internal to libares (5 seconds then 3 more retries increasingly spaced out). Doing another layer of this seems wrong and extending tries beyond 30 second mark seems excessive as well given we try again 90 seconds after that.
2. *Blocking resolution until DNS resolved* - The bootstrap_dns are optional so this would add minor mess to the logic there, but not hard to do if this is proven to be the root cause. (See above for theory about network interface devices possibly not being present/up at program startup.)
3. *Blocking execution until DNS resolved* - Also quite a bit of plumbing for a timing issue that may not be the fault of the program.

Could you possibly try logging your ifconfig output prior to starting the daemon? If that turns out to be your problem, I'm tempted to suggest "sleep 60;" as your solution. :)

**Comment by tofurky** [comment] 2018-09-10 01:29
the issue is definitely due to the script being started before the interface is up. i had suggested using an interface trigger i.e. `procd_add_interface_trigger`, however this didn't work in my brief testing of it. i'm not sure a "sleep" would be acceptable solution for the OpenWRT folks in their packages repo.

here's an example of how quickly it's failing compared to when the proxy is started:
```
[I] 1536339277.407242 main.c:177 Built Sep  7 2018 09:34:24.
[I] 1536339277.407569 main.c:178 System c-ares: 1.14.0
[I] 1536339277.407678 main.c:179 System libcurl: libcurl/7.61.0 OpenSSL/1.0.2p zlib/1.2.11 nghttp2/1.33.0
[I] 1536339277.653197 dns_server.c:39 Listening on 127.0.0.1:5053
[D] 1536339277.653282 logging.c:49 initializing periodic log flush timer
[I] 1536339277.654259 main.c:240 DNS polling initialized for 'cloudflare-dns.com'
[W] 1536339277.667608 dns_poller.c:43 DNS lookup failed: 11
[D] 1536339283.213378 main.c:115 Received request for 'accounts.google.com' id: 82a8, type 1, flags 0100
[D] 1536339283.213674 https_client.c:57 Requesting HTTP/1.1: 0
```
so you can see there's only < 1 second before it fails, only to try again 120s later. this makes me think that it's not actually retrying.

in my debugging i took a look at what the options looked like:
```
CONFIG_CHECK: lookups=0, nsort=-1, nservers=2, ndomains=-1, ndots=-1, timeout=-1, tries=-1
```
so perhaps the timeout and retries could be set via `init_by_options()`, as an alternative to more intensive refectoring? i'm not sure how quickly it'd expend any number of retries, as the error being returned `ARES_ECONNREFUSED` is actually a symptom of an immediate "no route to host" type error, i believe.

**Comment by tofurky** [comment] 2018-09-10 01:37
another thought i had was to modify the timer value during runtime. not quite as complicated as an exponential backoff, but per libev docs (and in my experience using it in perl) you could possibly:
  * make the timer non-repeating, and rearm the timer upon each firing in the ares callback. this would depend on success or failure - 120s on success, maybe something like 5s on failure.
  * initially set the timer to a smaller value. upon successful bootstrapping, stop timer, set timer, and rearm timer to the 120s value.

the 'd' struct is already being passed to `ares_cb()` as `arg`, so it wouldn't require a large amount of code changes.

**Comment by aarond10** [comment] 2018-09-10 02:31
Yeah, that sounds reasonable. If there is default route, the failure may be expediated. Did you want to send a pull request for the timer changes? I'm about done for the day. :) Otherwise, I'll take a crack some time over the next few days.

**Comment by tofurky** [comment] 2018-09-10 03:06
yeah i can try.

i just took a look at c-ares ares_gethostnameby.c/ares_search.c/ares_query.c, and unfortunately i don't think that changing the retries in c-ares will make any difference. since the icmp unreachable or similar is being returned more or less instantly, the timeout appears to be irrelevant. there also doesn't appear to be anything resembling a retry interval. so it just blasts them all off without any configurable delay.

i'll do some testing overnight and let you know if i come up with something. it'll probably look closer to the second option (smaller initial interval).

**Comment by tofurky** [comment] 2018-09-10 05:49
here's a rough draft (not intended as a PR or for otherwise merging as-is): https://github.com/tofurky/https_dns_proxy/commit/1c89f6ca129253aa9a2b4df198e7c8fd6c950470

i think it might be wiser to disable the repeating timer (when in "error" mode) and manually re-arm it during each invocation of ares_cb() because a 5s interval is less than the libcares defaults:

```
ARES_OPT_TIMEOUTMS int timeout; 
The number of milliseconds each name server is given to respond to a query on the first try. (After the first try, the timeout algorithm becomes more complicated, but scales linearly with the value of timeout.) The default is five seconds. Note that this option is specified with the same struct field as the former ARES_OPT_TIMEOUT, it is but the option bits that tell c-ares how to interpret the number. This option was added in c-ares 1.5.2.

ARES_OPT_TRIES int tries; 
The number of tries the resolver will try contacting each name server before giving up. The default is four tries.
```

that could possibly lead to multiple queries piling up because 5s <= 20s and cause some undefined/unintentional behavior.

changing it to manual re-arming would depend on ares_cb() being called unconditionally, but from what i understand it should *always* be called after ares_gethostbyname() is.

alternatively ares_init_options() could be modified to "guarantee" that ares_cb() will be called before the next repeating timer fires.

i'm also thinking that if the bootstrap dns servers are provided that the proxy shouldn't service any requests using curl/resolv.conf until it's bootstrapped. this would solve dns loop problem if resolv.conf points to (either directly or via dnsmasq) https_dns_proxy.

as i mentioned in the commit message, it does drastically reduce the time (23s vs 120s until bootstrapped).

**Comment by jefferyto** [comment] 2018-09-10 13:12
Apologies for the potentially stupid question, but is the network connection not being ready the root cause of this issue?

It's been a while since I tried to debug this so my memory of the results is a bit hazy, but if I'm not mistaken, the zero-length responses occurred even after I restarted the daemon when the network connection came up.

I noted in my original bug report that I had a hotplug script to restart the daemon whenever a network connection is up. Soon after submitting the report, I added a small daemon that tries a DNS lookup every 5 minutes and restarts this daemon if the request didn't succeed. I'm reasonably sure I had to do this because the issue was still present.

I hope my skepticism is understandable :smile:

**Comment by jefferyto** [comment] 2018-09-10 14:38
I'm all for things getting fixed :smile: thanks for your help!

**Comment by tofurky** [comment] 2018-09-10 17:32
here's a much better one that i think is ready for PR: https://github.com/tofurky/https_dns_proxy/commit/3869abcb33e82fe0e94eeabd04fb10fa544c1b1b

i changed a couple things, one of which was calling ares_cancel() in timer_cb(). it turns out that c-ares doesn't seem to be able to time-based timeouts when used alongside libev. if a packet is dropped, the callback is never run. only if an icmp unreachable or actual response is received will it execute the callback. this also means that dropped packets are potentially memory leaks. cancelling fixes this with no ill-effects and very much simplifies things.

this also discards replies until bootstrapped. this should fix any potential "dns loop" issues. i looked into what it'd take to issue a valid "ServFail" response and it seemed way too complex to implement for not much benefit.

i tested this a bunch on my PC while doing ifdown eth0/ifup eth0 and it seems to fix both the mentioned issues. there are more detailed comments in the patch that explains things a bit more.

in testing, queries are serviced ~10s after startup, vs. 120s.

one thing that just came to mind as i was writing this was the case of dropped packets, where ares_cb() is never called. perhaps starting with a smaller interval would make more sense. start off at 5s, continue until bootstrapped. i'll think about it.

here's a sample output (starting at boot from openwrt via procd):
```
[I] 1536599299.679170 main.c:185 Built Sep  7 2018 09:34:24.
[I] 1536599299.679218 main.c:186 System c-ares: 1.14.0
[I] 1536599299.679294 main.c:187 System libcurl: libcurl/7.61.0 OpenSSL/1.0.2p zlib/1.2.11 nghttp2/1.33.0
[I] 1536599300.188592 dns_server.c:39 Listening on 127.0.0.1:5053
[D] 1536599300.188678 logging.c:49 initializing periodic log flush timer
[I] 1536599300.218206 main.c:248 DNS polling initialized for 'cloudflare-dns.com'
[W] 1536599300.244856 dns_poller.c:46 DNS lookup failed: Could not contact DNS servers
[W] 1536599300.244931 dns_poller.c:56 DNS poll interval changed from 120 -> 5
[W] 1536599305.233656 dns_poller.c:46 DNS lookup failed: Could not contact DNS servers
[D] 1536599308.548689 main.c:115 Received request for 'www.mysqueezebox.com' id: e565, type 1, flags 0100
[W] 1536599308.548727 main.c:121 Query received before bootstrapping is completed, discarding.
[D] 1536599308.890513 main.c:115 Received request for 'hub-api.wink.com' id: 9a39, type 1, flags 0100
[W] 1536599308.890552 main.c:121 Query received before bootstrapping is completed, discarding.
[D] 1536599308.891089 main.c:115 Received request for 'hub-api.wink.com' id: e249, type 28, flags 0100
[W] 1536599308.891127 main.c:121 Query received before bootstrapping is completed, discarding.
[D] 1536599309.131373 main.c:115 Received request for 'clients6.google.com' id: e127, type 1, flags 0100
[W] 1536599309.131410 main.c:121 Query received before bootstrapping is completed, discarding.
[D] 1536599309.190117 main.c:115 Received request for 'mail.google.com' id: 5776, type 1, flags 0100
[W] 1536599309.190156 main.c:121 Query received before bootstrapping is completed, discarding.
[D] 1536599310.146228 main.c:115 Received request for '15.client-channel.google.com' id: 18c4, type 1, flags 0100
[W] 1536599310.146267 main.c:121 Query received before bootstrapping is completed, discarding.
[D] 1536599310.260107 main.c:154 Received new IP '104.16.111.25'
[W] 1536599310.260133 dns_poller.c:56 DNS poll interval changed from 5 -> 120
[D] 1536599311.151904 main.c:115 Received request for 'clients6.google.com' id: 482c, type 1, flags 0100
[D] 1536599311.152192 https_client.c:57 Requesting HTTP/1.1: 0

[D] 1536599312.264543 main.c:115 Received request for 'notifications.google.com' id: ba27, type 1, flags 0100
[D] 1536599312.265625 https_client.c:57 Requesting HTTP/1.1: 0

[D] 1536599312.763821 main.c:115 Received request for 'spectrum.s3.amazonaws.com' id: d7f9, type 1, flags 0100
[D] 1536599312.764104 https_client.c:57 Requesting HTTP/1.1: 0

[D] 1536599312.765109 main.c:115 Received request for 'd3p8zr0ffa9t17.cloudfront.net' id: 7d29, type 1, flags 0100
[D] 1536599312.765966 https_client.c:57 Requesting HTTP/1.1: 0

[D] 1536599312.767587 https_client.c:96 CURLINFO_EFFECTIVE_URL: https://cloudflare-dns.com/dns-query?ct=application/dns-json&name=clients6.google.com&type=1
[D] 1536599312.767630 https_client.c:169 Times: 0.000202, 0.017934, 1.122062, 1.123260, 1.614958, 1.615199
[D] 1536599312.767744 main.c:80 buflen 727

[D] 1536599312.767769 main.c:94 Received response for id 482c: {"Status": 0,"TC": false,"RD": true, "RA": true, "AD": false,"CD": false,"Question":[{"name": "clients6.google.com.", "type": 1}],"Answer":[{"name": "clients6.google.com.", "type": 5, "TTL": 92, "data": "clients.l.google.com."},{"name": "clients.l.google.com.", "type": 1, "TTL": 121, "data": "64.233.185.100"},{"name": "clients.l.google.com.", "type": 1, "TTL": 121, "data": "64.233.185.101"},{"name": "clients.l.google.com.", "type": 1, "TTL": 121, "data": "64.233.185.102"},{"name": "clients.l.google.com.", "type": 1, "TTL": 121, "data": "64.233.185.113"},{"name": "clients.l.google.com.", "type": 1, "TTL": 121, "data": "64.233.185.138"},{"name": "clients.l.google.com.", "type": 1, "TTL": 121, "data": "64.233.185.139"}]}
```

**Comment by tofurky** [comment] 2018-09-13 03:00
@jefferyto et al. you could try bumping the PKG_SRC_VERSION in the openwrt makefile to 4ef39c5a87a60313969f4711c4c7a5fbf1858a44 and rebuilding to see if it fixes the issue. it has the fixes for bootstrapping and potential dns loops. mostly it'll speed up the startup by about 10x (10s vs 120s in my tests) and might help with the cpu spikes at startup as well. thanks @aarond10 for your help with getting that merged!

**Comment by jefferyto** [comment] 2018-10-01 04:31
Thanks @tofurky for your help - I've had to uninstall the proxy for unrelated reasons so I'm unable to test this at this time. I hope some of the other commenters can have a go at it.

**Closed** 2018-10-01 07:14 UTC
